name: Make release on "VERSION" file change @ main

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  checks_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run CI
        run: |
          make check PYTHON=python3
          make tests PYTHON=python3
  

  build_windows:
    needs: checks_and_tests
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - run: choco install make
      - name: Build Binary
        run: |
          make build_windows PYINSTALLER=pyinstaller
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: windows.zip
          path: dist/windows.zip

  build_linux:
    needs: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Build Binary
        run: |
          make build_linux_macos PYINSTALLER=pyinstaller
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: linux.tar.gz
          path: dist/linux_macos.tar.gz

  build_macos:
    needs: checks_and_tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Build Binary
        run: |
          make build_linux_macos PYINSTALLER=pyinstaller
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: macos.tar.gz
          path: dist/linux_macos.tar.gz

  release:
    needs:
      - build_windows
      - build_macos
      - build_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - uses: actions/download-artifact@v2
        with:
          name: windows.zip
          path: artifacts/
      - uses: actions/download-artifact@v2
        with:
          name: linux.tar.gz
          path: artifacts/
      - uses: actions/download-artifact@v2
        with:
          name: macos.tar.gz
          path: artifacts/

      - run: |
          cd artifacts
          mv windows.zip "birthday-reminder-windows-v$(cat VERSION).zip"
          mv linux.tar.gz "birthday-reminder-linux-v$(cat VERSION).tar.gz"
          mv macos.tar.gz "birthday-reminder-macOS-v$(cat VERSION).tar.gz"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Birthday Reminder ${{ steps.get_version.outputs.version }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
